window:
  dimensions:
    columns: 120
    lines: 36
  padding:
    x: 0
    y: 0
  dynamic_padding: true
  dynamic_title: true
  gtk_theme_variant: None

scrolling:
  history: 10000

font:
  normal:
    family: Cascadia Code
    style: SemiBold
  bold:
    family: Cascadia Code
    style: Bold
  italic:
    family: Cascadia Code
    style: Italic
  size: 10

draw_bold_text_with_bright_colors: true

# Colors (Gruvbox dark)
colors:
  # Default colors
  primary:
    # hard contrast: background = '#1d2021'
    background: '#282828'
    # soft contrast: background = '#32302f'
  foreground: '#ebdbb2'

  normal:
    black:   '#282828'
    red:     '#cc241d'
    green:   '#98971a'
    yellow:  '#d79921'
    blue:    '#458588'
    magenta: '#b16286'
    cyan:    '#689d6a'
    white:   '#a89984'

  bright:
    black:   '#928374'
    red:     '#fb4934'
    green:   '#b8bb26'
    yellow:  '#fabd2f'
    blue:    '#83a598'
    magenta: '#d3869b'
    cyan:    '#8ec07c'
    white:   '#ebdbb2'

  cursor:
    text: CellBackground
    cursor: CellForeground

selection:
  save_to_clipboard: true

cursor:
  unfocused_hollow: true

live_config_reload: true

mouse:
  url:
    launcher:
      program: xdg-open

key_bindings:
  - { key: N, mods: Control|Shift, action: SpawnNewInstance }
  - { key: Equals, mods: Control, action: IncreaseFontSize }
  - { key: Minus, mods: Control, action: DecreaseFontSize }
  - { key: 0, mods: Control, action: ResetFontSize }
