cask_args appdir: "~/Applications"

tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/cask"

brew "git-delta"
brew "nvm"
brew "tmux"
brew "tree"

cask "discord"
cask "dropbox"
cask "firefox"
cask "google-chrome"
cask "insomnia"
cask "linear-linear"
cask "mysqlworkbench"
cask "visual-studio-code"
cask "zoom"
