cask_args appdir: "~/Applications"
tap "d12frosted/emacs-plus"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "mongodb/brew"

brew "bat"
brew "clisp"
brew "fd"
brew "git-delta"
brew "go"
brew "jq"
brew "lua"
brew "mas"
brew "mysql"
brew "neovim"
brew "nvm"
brew "pyenv"
brew "ripgrep"
brew "sbcl"
brew "tldr"
brew "tmux"
brew "tree"
brew "zsh-autosuggestions"
brew "zsh-history-substring-search"
brew "zsh-syntax-highlighting"
brew "d12frosted/emacs-plus/emacs-plus@27"
brew "mongodb/brew/mongodb-community"

cask "alacritty"
cask "calibre"
cask "discord"
cask "dropbox"
cask "epic-games"
cask "firefox"
cask "font-caskaydia-cove-nerd-font"
cask "github"
cask "google-chrome"
cask "insomnia"
cask "libreoffice"
cask "linear-linear"
cask "microsoft-auto-update"
cask "microsoft-edge"
cask "mochi"
cask "mysqlworkbench"
cask "notion"
cask "numi"
cask "obsidian"
cask "openemu"
cask "postman"
cask "rectangle"
cask "selfcontrol"
cask "spotify"
cask "steam"
cask "temurin"
cask "ultdata"
cask "visual-studio-code"
cask "zoom"

mas "AdBlock", id: 1402042596
mas "Amphetamine", id: 937984704
mas "Bandwidth+", id: 490461369
mas "Flow", id: 1423210932
mas "Meeter", id: 1510445899
mas "NetWorker Lite", id: 1228738830
mas "Vimari", id: 1480933944
