# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"
export DOTFILES="$HOME/.dotfiles"

ZSH_THEME="powerlevel10k/powerlevel10k"

# Uncomment the following line if pasting URLs and other text is messed up.
DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Have alias-finder run automatically before each command.
ZSH_ALIAS_FINDER_AUTOMATIC="true"

# Plugins
# Linux
plugins=(git colored-man-pages command-not-found zsh-autosuggestions zsh-syntax-highlighting)

# Mac. Most of the pluginstall are install by brew
# plugins=(git colored-man-pages command-not-found)

source $ZSH/oh-my-zsh.sh

alias v="nvim"
alias q="exit"

# tmux ide setup
alias df="~/.dotfiles/"

# tee-mocks
alias tt="tmux"

# tmux ide setup
alias sss="~/dotfiles/tmux/ide.sh"

# Linux Stuff
alias update="sudo apt-get update"
alias upgrade="sudo apt-get upgrade"
alias dist-upgrade="sudo apt-get dist-upgrade"
alias cleanup="sudo apt-get autoclean && sudo apt-get autoremove"

# Mac Stuff
# zsh-syntax-highlighting
# source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
#
# zsh-autosuggestions
# source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
#
# zsh-history-substring-search
# source /usr/local/share/zsh-history-substring-search/zsh-history-substring-search.zsh
# bindkey '^[OA' history-substring-search-up
# bindkey '^[OB' history-substring-search-down

# NVM path
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
#
# Enable p10k by uncommenting the code below
# [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Export pyenv path
# export PYENV_ROOT="$HOME/.pyenv"
# export PATH="$PYENV_ROOT/bin:$PATH"
# eval "$(pyenv init --path)"

# alias luamake=/Users/rmdm/Temp/lua-language-server/3rd/luamake/compile/luamake

source $HOME/.cargo/env

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

